services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "9545:9545"
    networks:
      - app-network
    command:
      - -h
      - "0.0.0.0"
      - -p
      - "9545"
      - -i
      - "5777"
      - -m
      - "test test test test test test test test test test test junk"
      - --gasLimit
      - "8000000"

  contracts:
    build: ./contracts
    depends_on:
      - ganache
    networks:
      - app-network
    volumes:
      - ./contracts/build:/contracts/build
    command: sh -c "./wait-for-ganache.sh && truffle migrate --reset --network development && tail -f /dev/null"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./contracts/build/contracts:/app/src/build-contracts

networks:
  app-network:
    driver: bridge

