services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "9545:9545"
    networks:
      - app-network
    command:
      - -h
      - "0.0.0.0"
      - -p
      - "9545"
      - -i
      - "5777"
      - -m
      - "test test test test test test test test test test test junk"

  contracts:
    build: ./contracts
    depends_on:
      - ganache
    networks:
      - app-network
    command: sh -c "./wait-for-ganache.sh"
    volumes:
      - ./contracts:/app

  test:
    build: ./test
    depends_on:
      - contracts
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./test:/app
      - ./contracts/build/contracts:/app/src/build-contracts

networks:
  app-network:
    driver: bridge

